spring:
  mail:
    # default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: skawuma69@gmail.com
    password: debo wust nvcs xnvd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
